import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // General
    "app.title": "Montega",
    "app.subtitle": "Carnes y Cortes Finos",
    
    // Login Mode Titles
    "login.title.login": "Acceso Exclusivo",
    "login.title.register": "Solicitud de Membresía",
    "login.title.verify": "Verificación de Identidad",
    "login.title.forgot": "Recuperar Cuenta",
    "login.title.reset": "Restablecer Contraseña",
    
    // Login Form Fields & Labels
    "login.label.name": "Nombre completo",
    "login.placeholder.name": "Ej. Juan Pérez",
    "login.label.email": "Correo electrónico",
    "login.placeholder.email": "correo@ejemplo.com",
    "login.label.password": "Contraseña",
    "login.placeholder.password": "••••••••",
    "login.label.confirmPassword": "Confirmar contraseña",
    "login.label.code": "Código de Verificación",
    "login.label.recoveryCode": "Código de Recuperación",
    "login.label.newPassword": "Nueva Contraseña",
    
    // Login Buttons & Toggles
    "login.button.loginTab": "Ingresar",
    "login.button.registerTab": "Registrar",
    "login.button.forgotPassword": "¿Olvidaste tu contraseña?",
    "login.button.submit.verify": "Verificar y Entrar",
    "login.button.submit.login": "Acceder al Catálogo",
    "login.button.submit.forgot": "Enviar Código",
    "login.button.submit.reset": "Restablecer",
    "login.button.submit.register": "Solicitar Acceso",
    "login.button.backToLogin": "Volver al inicio de sesión",
    "login.text.notMember": "¿Aún no eres miembro? ",
    "login.text.join": "Únete aquí",
    "login.text.alreadyMember": "¿Ya tienes membresía? ",
    "login.text.signIn": "Inicia Sesión",
    
    // Login Info / Descriptions
    "login.desc.verify": "Ingresa el código de 6 dígitos que enviamos a ",
    "login.desc.forgot": "Ingresa tu correo para enviarte un código de recuperación.",
    "login.desc.reset": "Ingresa el código enviado y tu nueva contraseña.",
    "login.resend.cooldown": "Reenviar en ",
    "login.resend.button": "¿No recibiste el código? Reenviar",
    
    // Client Navigation (Navbar)
    "nav.home": "Inicio",
    "nav.catalog": "Catálogo",
    "nav.cart": "Mi Carrito",
    "nav.orders": "Mis Pedidos",
    "nav.favorites": "Favoritos",
    "nav.wholesale": "Portal Mayorista",
    "nav.invoices": "Facturación",
    "nav.signout": "Cerrar Sesión",
    "nav.admin": "Panel de Control",
    "nav.navigation": "Navegación",
    "nav.administration": "Administración",
    "nav.quality": "Calidad Premium Garantizada",
    
    // Admin Navigation
    "admin.nav.dashboard": "Resumen",
    "admin.nav.orders": "Pedidos",
    "admin.nav.products": "Productos",
    "admin.nav.users": "Usuarios",
    "admin.nav.wholesale": "Mayoristas",

    // Catalog Page
    "catalog.hero.bannerTitle": "Productos Frescos del Día",
    "catalog.hero.title": "Carnicería Montega",
    "catalog.hero.desc": "La mejor selección de carnes, mariscos y más. Calidad garantizada para tu mesa.",
    "catalog.hero.countSuffix": "productos",
    "catalog.searchPlaceholder": "Buscar productos...",
    "catalog.foundSingular": "producto encontrado",
    "catalog.foundPlural": "productos encontrados",
    "catalog.noProducts": "No se encontraron productos",

    // Category Filter
    "cat.all": "Todos",
    "cat.CERDO": "Cerdo",
    "cat.RES": "Res",
    "cat.BORREGO": "Borrego",
    "cat.POLLO": "Pollo",
    "cat.MARISCOS": "Mariscos",
    "cat.PAPAS": "Papas & Snacks",
    "cat.VARIOS": "Varios",

    // Product Card
    "card.addedToast": "agregado al carrito",
    "card.defaultDesc": "Corte premium seleccionado del obrador.",
    "card.addToCart": "Agregar al carrito",
    "card.wholesale.ok": "MAYOREO OK",
    "card.wholesale.badge": "MAYOREO (40 kilos)",

    // Review Section
    "review.reviewSingular": "reseña",
    "review.reviewPlural": "reseñas",
    "review.noReviews": "Sin reseñas aún",
    "review.opinionBtn": "Opinar",
    "review.placeholder": "Escribe tu opinión...",
    "review.publish": "Publicar",
    "review.cancel": "Cancelar",
    "review.thanks": "¡Gracias por tu reseña!",
    "review.defaultName": "Cliente",

    // Favorites Page
    "favorites.title": "Mis Favoritos",
    "favorites.noFavorites": "Aún no tienes favoritos",
    "favorites.viewCatalog": "Ver Catálogo",
    "favorites.addToCart": "Agregar al carrito",
    "favorites.addedToast": "agregado al carrito",

    // Invoices Page
    "invoices.title": "Mis Facturas",
    "invoices.desc": "Historial de recibos y comprobantes de compra",
    "invoices.noInvoices": "Sin facturas disponibles",
    "invoices.noInvoicesDesc": "Tus facturas aparecerán aquí una vez que realices pedidos en la tienda.",
    "invoices.th.date": "Fecha",
    "invoices.th.folio": "Folio",
    "invoices.th.status": "Estado",
    "invoices.th.total": "Total",
    "invoices.th.action": "Acción",
    "invoices.downloadSuccess": "Factura descargada con éxito",
    "invoices.downloadError": "Error al generar la factura",
    "invoices.about.title": "Sobre tus comprobantes",
    "invoices.about.desc": "Estos documentos son recibos de compra generados por el sistema. Si requiere una factura fiscal (CFDI) con datos específicos de facturación, por favor contáctenos directamente a través de nuestro WhatsApp de atención al cliente.",

    // Wholesale Page
    "wholesale.hero.tagline": "Alianzas Estratégicas",
    "wholesale.hero.title": "Surtimos la Excelencia en tu Negocio",
    "wholesale.hero.desc": "Únete a la red de restaurantes y hoteles que confían en Montega para ofrecer los mejores cortes a sus comensales.",
    "wholesale.benefit1.title": "Calidad Certificada",
    "wholesale.benefit1.desc": "Cortes premium seleccionados con los más altos estándares de higiene y frescura.",
    "wholesale.benefit2.title": "Logística Eficiente",
    "wholesale.benefit2.desc": "Entregas programadas y prioritarias para asegurar que tu negocio nunca se detenga.",
    "wholesale.benefit3.title": "Precios Especiales",
    "wholesale.benefit3.desc": "Escalas de precios competitivas diseñadas para maximizar la rentabilidad de tu negocio.",
    "wholesale.quickHelp.title": "¿Necesitas asesoría rápida?",
    "wholesale.quickHelp.desc": "Nuestro equipo de ventas está disponible para atenderte personalmente.",
    "wholesale.form.title": "Solicitud de Cotización",
    "wholesale.form.businessName": "Nombre del Negocio *",
    "wholesale.form.businessNamePlaceholder": "Ej: Restaurante El Corte",
    "wholesale.form.businessType": "Tipo de Negocio",
    "wholesale.form.businessType.restaurant": "Restaurante",
    "wholesale.form.businessType.hotel": "Hotel",
    "wholesale.form.businessType.catering": "Catering / Eventos",
    "wholesale.form.businessType.distributor": "Distribuidor",
    "wholesale.form.businessType.other": "Otro",
    "wholesale.form.contactName": "Contacto Responsable *",
    "wholesale.form.contactNamePlaceholder": "Tu nombre completo",
    "wholesale.form.phone": "Teléfono de Contacto *",
    "wholesale.form.phonePlaceholder": "10 dígitos",
    "wholesale.form.email": "Correo Electrónico *",
    "wholesale.form.emailPlaceholder": "ejemplo@negocio.com",
    "wholesale.form.volume": "Volumen Estimado Semanal (kg)",
    "wholesale.form.volumePlaceholder": "Ej: 50-100 kg",
    "wholesale.form.message": "Mensaje / Requerimientos",
    "wholesale.form.messagePlaceholder": "¿Qué cortes te interesan? ¿Tienes alguna duda específica?",
    "wholesale.form.submit": "Enviar Solicitud",
    "wholesale.form.disclaimer": "Al enviar aceptas que un asesor te contacte vía WhatsApp o correo electrónico.",
    "wholesale.success.title": "¡Solicitud Recibida!",
    "wholesale.success.desc": "Gracias por tu interés en Montega. Un ejecutivo de cuentas clave se pondrá en contacto contigo en las próximas 24 horas.",
    "wholesale.success.back": "Volver a empezar",

    // Orders Page
    "orders.title": "Mis Pedidos",
    "orders.noOrders": "Sin pedidos aún",
    "orders.noOrdersDesc": "Tus pedidos aparecerán aquí una vez que compres",
    "orders.countSuffix": "pedido en total",
    "orders.countSuffixPlural": "pedidos en total",
    "orders.orderNumber": "Pedido",
    "orders.totalOrder": "Total del pedido",
    "orders.paymentPending": "Pago pendiente.",
    "orders.paymentPendingDesc": "Presenta tu pedido en caja para completar la compra.",
    "orders.cancelOrder": "Cancelar pedido",
    "orders.cancelConfirm": "¿Seguro que deseas cancelar este pedido?",
    "orders.refundWarning": "⚠️ Como tu pedido ya fue pagado, el reembolso será procesado manualmente y puede tardar de 3 a 5 días hábiles en reflejarse en tu cuenta.",
    "orders.cancelYes": "Sí, cancelar",
    "orders.cancelNo": "No",
    "orders.cancelSuccess": "Pedido cancelado",
    "orders.downloadReceipt": "Descargar Recibo (PDF)",
    "orders.downloadSuccess": "Factura descargada con éxito",
    "orders.downloadError": "Error al generar la factura: ",
    "orders.status.pendiente": "Pendiente de Pago",
    "orders.status.confirmado": "Pago Confirmado",
    "orders.status.en_preparacion": "En Preparación",
    "orders.status.listo": "Listo para Recoger",
    "orders.status.entregado": "Entregado ✓",
    "orders.status.cancelado": "Cancelado",

    // Cart Page
    "cart.title": "Mi Carrito",
    "cart.empty": "Tu carrito está vacío",
    "cart.emptyDesc": "Agrega productos para comenzar",
    "cart.viewCatalog": "Ver Catálogo",
    "cart.clear": "Vaciar",
    "cart.wholesale.benefitTitle": "Beneficio de Mayoreo Activado",
    "cart.wholesale.benefitDesc": "Has alcanzado el mínimo de 40 kilos para mayoreo. Se han aplicado precios especiales a todos los productos elegibles.",
    "cart.wholesale.goalTitle": "Beneficio Mayoreo: Meta 40 kilos",
    "cart.wholesale.goalDesc1": "Te faltan ",
    "cart.wholesale.goalDesc2": " kilos para activar los precios especiales.",
    "cart.delivery.title": "Detalles de Entrega",
    "cart.delivery.phone": "Teléfono de contacto",
    "cart.delivery.phonePlaceholder": "Ej: 55 1234 5678",
    "cart.delivery.notes": "Notas Especiales",
    "cart.delivery.notesPlaceholder": "Instrucciones de corte, preferencias, etc.",
    "cart.payment.title": "Pago Seguro",
    "cart.payment.desc": "Transacción encriptada de 256 bits.",
    "cart.payment.sandbox": "Modo de Pruebas Activo",
    "cart.payment.sandboxDesc": "Estás en el entorno de desarrollo (Sandbox). Para simular tu compra de forma exitosa, haz clic en una de nuestras tarjetas de prueba para rellenar los datos automáticamente:",
    "cart.payment.cardName": "Nombre en la Tarjeta",
    "cart.payment.cardNamePlaceholder": "Ej. Juan Pérez",
    "cart.payment.cardNumber": "Número de Tarjeta",
    "cart.payment.cardMonth": "Mes",
    "cart.payment.cardYear": "Año",
    "cart.payment.cardCvv": "CVV",
    "cart.payment.total": "Total Final",
    "cart.payment.taxIncluded": "Impuestos incluidos",
    "cart.payment.buttonPay": "Confirmar y Pagar",
    "cart.payment.buttonProcessing": "Procesando Pago...",
    "cart.payment.securityInfo": "Seguridad garantizada por OpenPay de BBVA",

    // Home Page
    "home.hero.tagline": "Arte en Carnicería",
    "home.hero.title": "Montega",
    "home.hero.title2": "",
    "home.hero.desc": "Selección exclusiva de cortes premium. El estándar de oro para tu mesa.",
    "home.hero.buttonCatalog": "Explorar Catálogo",
    "home.hero.buttonContact": "Contacto Directo",
    "home.hero.scroll": "Descubrir",
    "home.stats.years": "Años de maestría",
    "home.stats.cuts": "Cortes exclusivos",
    "home.stats.guarantee": "Garantía de origen",
    "home.stats.region": "En la región",
    "home.catalog.tagline": "Colección Premium",
    "home.catalog.desc": "Nuestra selección más exclusiva. Carnes maduradas y cortes especiales elegidos minuciosamente.",
    "home.catalog.beef": "Cortes Finos de Res",
    "home.catalog.pork": "Cerdo Premium",
    "home.catalog.poultry": "Aves Frescas",
    "home.catalog.seafood": "Del Mar",
    "home.catalog.button": "Ver Catálogo Completo",
    "home.about.title": "La perfección no se apura, se cultiva.",
    "home.about.desc1": "En Montega, entendemos que un corte excepcional requiere maestría, tiempo y dedicación. Durante más de dos décadas, hemos perfeccionado el arte de la selección y maduración cárnica.",
    "home.about.desc2": "No somos solo una carnicería; somos curadores de sabor. Trabajamos en estrecha colaboración con las mejores ganaderías para garantizar que cada pieza que lleva nuestro sello cumpla con los estándares más rigurosos de marmoleo, textura y sabor.",
    "home.about.sealTitle": "Calidad Suprema",
    "home.about.sealDesc": "Firma de excelencia",
    "home.feature1.title": "Calidad Prime",
    "home.feature1.desc": "Seleccionamos a mano los mejores cortes del obrador para los paladares más exigentes.",
    "home.feature2.title": "Fresco Diario",
    "home.feature2.desc": "Procesamiento artesanal diario. Del obrador a tu mesa conservando el máximo sabor.",
    "home.feature3.title": "Entrega VIP",
    "home.feature3.desc": "Transporte en cadena de frío para que tu pedido llegue en condiciones óptimas.",
    "home.feature4.title": "Herencia Familiar",
    "home.feature4.desc": "Dos décadas perfeccionando el arte de la carnicería fina.",
    "home.contact.title": "Servicio Personalizado",
    "home.contact.desc": "Nuestros carniceros expertos están a su disposición para asesorarle sobre el corte perfecto para su ocasión.",
    "home.contact.phoneTag": "Línea Directa",
    "home.contact.emailTag": "Atención VIP",
    "home.contact.whatsappButton": "Asesoría por WhatsApp",
    "home.footer.desc": "Excelencia en cada corte.",

    // Product Detail Page
    "detail.notFound": "Producto no encontrado",
    "detail.viewCatalog": "Ver Catálogo",
    "detail.back": "Volver al catálogo",
    "detail.noStock": "Sin stock",
    "detail.reviews": "reseñas",
    "detail.normalPrice": "Precio normal",
    "detail.wholesale.applied": "PRECIO MAYOREO APLICADO",
    "detail.wholesale.available": "PRECIO MAYOREO DISPONIBLE",
    "detail.wholesale.badge": "Mayoreo (40 kilos)",
    "detail.wholesale.benefit": "Beneficio de Mayoreo",
    "detail.wholesale.reached1": "Alcanza un total de ",
    "detail.wholesale.reached2": " en tu carrito para activar el precio especial. (Llevas ",
    "detail.wholesale.reached3": "kg)",
    "detail.ingredient": "Ingrediente principal",
    "detail.qty": "Cantidad (kg)",
    "detail.add": "Agregar",
    "detail.addedSuccess": "{qty} kg de {name} agregado al carrito",

    // Order Success Page
    "success.title": "¡Pago exitoso!",
    "success.desc": "Tu pedido fue confirmado. Recibirás un email de confirmación y podrás rastrear el estado en \"Mis Pedidos\".",
    "success.orderId": "Pedido #",
    "success.download": "Descargar Ticket PDF",
    "success.viewOrders": "Ver mis pedidos",
    "success.continue": "Seguir comprando",
  },
  en: {
    // General
    "app.title": "Montega",
    "app.subtitle": "Premium Meats & Fine Cuts",
    
    // Login Mode Titles
    "login.title.login": "Exclusive Access",
    "login.title.register": "Membership Request",
    "login.title.verify": "Identity Verification",
    "login.title.forgot": "Recover Account",
    "login.title.reset": "Reset Password",
    
    // Login Form Fields & Labels
    "login.label.name": "Full Name",
    "login.placeholder.name": "e.g. John Doe",
    "login.label.email": "Email Address",
    "login.placeholder.email": "email@example.com",
    "login.label.password": "Password",
    "login.placeholder.password": "••••••••",
    "login.label.confirmPassword": "Confirm Password",
    "login.label.code": "Verification Code",
    "login.label.recoveryCode": "Recovery Code",
    "login.label.newPassword": "New Password",
    
    // Login Buttons & Toggles
    "login.button.loginTab": "Sign In",
    "login.button.registerTab": "Sign Up",
    "login.button.forgotPassword": "Forgot password?",
    "login.button.submit.verify": "Verify & Enter",
    "login.button.submit.login": "Access Catalog",
    "login.button.submit.forgot": "Send Code",
    "login.button.submit.reset": "Reset Password",
    "login.button.submit.register": "Request Access",
    "login.button.backToLogin": "Back to Login",
    "login.text.notMember": "Not a member yet? ",
    "login.text.join": "Join here",
    "login.text.alreadyMember": "Already a member? ",
    "login.text.signIn": "Sign In",
    
    // Login Info / Descriptions
    "login.desc.verify": "Enter the 6-digit code we sent to ",
    "login.desc.forgot": "Enter your email to receive a recovery code.",
    "login.desc.reset": "Enter the verification code and your new password.",
    "login.resend.cooldown": "Resend in ",
    "login.resend.button": "Didn't receive the code? Resend",
    
    // Client Navigation (Navbar)
    "nav.home": "Home",
    "nav.catalog": "Catalog",
    "nav.cart": "My Cart",
    "nav.orders": "My Orders",
    "nav.favorites": "Favorites",
    "nav.wholesale": "Wholesale Portal",
    "nav.invoices": "Invoicing",
    "nav.signout": "Sign Out",
    "nav.admin": "Admin Panel",
    "nav.navigation": "Navigation",
    "nav.administration": "Administration",
    "nav.quality": "Guaranteed Premium Quality",
    
    // Admin Navigation
    "admin.nav.dashboard": "Overview",
    "admin.nav.orders": "Orders",
    "admin.nav.products": "Products",
    "admin.nav.users": "Users",
    "admin.nav.wholesale": "Wholesalers",

    // Catalog Page
    "catalog.hero.bannerTitle": "Fresh Products of the Day",
    "catalog.hero.title": "Montega Butcher",
    "catalog.hero.desc": "The best selection of meats, seafood, and more. Guaranteed quality for your table.",
    "catalog.hero.countSuffix": "products",
    "catalog.searchPlaceholder": "Search products...",
    "catalog.foundSingular": "product found",
    "catalog.foundPlural": "products found",
    "catalog.noProducts": "No products found",

    // Category Filter
    "cat.all": "All",
    "cat.CERDO": "Pork",
    "cat.RES": "Beef",
    "cat.BORREGO": "Lamb",
    "cat.POLLO": "Poultry",
    "cat.MARISCOS": "Seafood",
    "cat.PAPAS": "Potatoes & Snacks",
    "cat.VARIOS": "Other",

    // Product Card
    "card.addedToast": "added to cart",
    "card.defaultDesc": "Premium cut selected from our workshop.",
    "card.addToCart": "Add to cart",
    "card.wholesale.ok": "WHOLESALE OK",
    "card.wholesale.badge": "WHOLESALE (40 kilos)",

    // Review Section
    "review.reviewSingular": "review",
    "review.reviewPlural": "reviews",
    "review.noReviews": "No reviews yet",
    "review.opinionBtn": "Review",
    "review.placeholder": "Write your review...",
    "review.publish": "Publish",
    "review.cancel": "Cancel",
    "review.thanks": "Thank you for your review!",
    "review.defaultName": "Customer",

    // Favorites Page
    "favorites.title": "My Favorites",
    "favorites.noFavorites": "No favorites yet",
    "favorites.viewCatalog": "View Catalog",
    "favorites.addToCart": "Add to cart",
    "favorites.addedToast": "added to cart",

    // Invoices Page
    "invoices.title": "My Invoices",
    "invoices.desc": "History of receipts and purchase vouchers",
    "invoices.noInvoices": "No invoices available",
    "invoices.noInvoicesDesc": "Your invoices will appear here once you make orders in the store.",
    "invoices.th.date": "Date",
    "invoices.th.folio": "Folio",
    "invoices.th.status": "Status",
    "invoices.th.total": "Total",
    "invoices.th.action": "Action",
    "invoices.downloadSuccess": "Invoice downloaded successfully",
    "invoices.downloadError": "Error generating invoice",
    "invoices.about.title": "About your vouchers",
    "invoices.about.desc": "These documents are purchase receipts generated by the system. If you require a tax invoice (CFDI) with specific billing details, please contact us directly via our customer support WhatsApp.",

    // Wholesale Page
    "wholesale.hero.tagline": "Strategic Alliances",
    "wholesale.hero.title": "We Supply Excellence to Your Business",
    "wholesale.hero.desc": "Join the network of restaurants and hotels that trust Montega to offer the best cuts to their guests.",
    "wholesale.benefit1.title": "Certified Quality",
    "wholesale.benefit1.desc": "Premium cuts selected under the highest hygiene and freshness standards.",
    "wholesale.benefit2.title": "Efficient Logistics",
    "wholesale.benefit2.desc": "Scheduled and priority deliveries to ensure your business never stops.",
    "wholesale.benefit3.title": "Special Pricing",
    "wholesale.benefit3.desc": "Competitive pricing scales designed to maximize your business profitability.",
    "wholesale.quickHelp.title": "Need quick advice?",
    "wholesale.quickHelp.desc": "Our sales team is available to assist you personally.",
    "wholesale.form.title": "Quote Request",
    "wholesale.form.businessName": "Business Name *",
    "wholesale.form.businessNamePlaceholder": "e.g. Steak House Restaurant",
    "wholesale.form.businessType": "Business Type",
    "wholesale.form.businessType.restaurant": "Restaurant",
    "wholesale.form.businessType.hotel": "Hotel",
    "wholesale.form.businessType.catering": "Catering / Events",
    "wholesale.form.businessType.distributor": "Distributor",
    "wholesale.form.businessType.other": "Other",
    "wholesale.form.contactName": "Responsible Contact *",
    "wholesale.form.contactNamePlaceholder": "Your full name",
    "wholesale.form.phone": "Contact Phone *",
    "wholesale.form.phonePlaceholder": "10 digits",
    "wholesale.form.email": "Email Address *",
    "wholesale.form.emailPlaceholder": "example@business.com",
    "wholesale.form.volume": "Estimated Weekly Volume (kg)",
    "wholesale.form.volumePlaceholder": "e.g. 50-100 kg",
    "wholesale.form.message": "Message / Requirements",
    "wholesale.form.messagePlaceholder": "Which cuts are you interested in? Any specific questions?",
    "wholesale.form.submit": "Send Request",
    "wholesale.form.disclaimer": "By sending, you agree that an advisor may contact you via WhatsApp or email.",
    "wholesale.success.title": "Request Received!",
    "wholesale.success.desc": "Thank you for your interest in Montega. A key account executive will contact you within the next 24 hours.",
    "wholesale.success.back": "Start over",

    // Orders Page
    "orders.title": "My Orders",
    "orders.noOrders": "No orders yet",
    "orders.noOrdersDesc": "Your orders will appear here once you buy",
    "orders.countSuffix": "order in total",
    "orders.countSuffixPlural": "orders in total",
    "orders.orderNumber": "Order",
    "orders.totalOrder": "Order total",
    "orders.paymentPending": "Pending payment.",
    "orders.paymentPendingDesc": "Present your order at checkout to complete the purchase.",
    "orders.cancelOrder": "Cancel order",
    "orders.cancelConfirm": "Are you sure you want to cancel this order?",
    "orders.refundWarning": "⚠️ Since your order has already been paid, the refund will be processed manually and may take 3 to 5 business days to reflect in your account.",
    "orders.cancelYes": "Yes, cancel",
    "orders.cancelNo": "No",
    "orders.cancelSuccess": "Order cancelled",
    "orders.downloadReceipt": "Download Receipt (PDF)",
    "orders.downloadSuccess": "Invoice downloaded successfully",
    "orders.downloadError": "Error generating invoice: ",
    "orders.status.pendiente": "Pending Payment",
    "orders.status.confirmado": "Payment Confirmed",
    "orders.status.en_preparacion": "In Preparation",
    "orders.status.listo": "Ready for Pickup",
    "orders.status.entregado": "Delivered ✓",
    "orders.status.cancelado": "Cancelled",

    // Cart Page
    "cart.title": "My Cart",
    "cart.empty": "Your cart is empty",
    "cart.emptyDesc": "Add products to get started",
    "cart.viewCatalog": "View Catalog",
    "cart.clear": "Clear",
    "cart.wholesale.benefitTitle": "Wholesale Benefit Activated",
    "cart.wholesale.benefitDesc": "You have reached the 40 kg minimum for wholesale. Special pricing has been applied to all eligible products.",
    "cart.wholesale.goalTitle": "Wholesale Benefit: 40 kg Goal",
    "cart.wholesale.goalDesc1": "You need ",
    "cart.wholesale.goalDesc2": " more kilos to activate special pricing.",
    "cart.delivery.title": "Delivery Details",
    "cart.delivery.phone": "Contact Phone",
    "cart.delivery.phonePlaceholder": "e.g. 55 1234 5678",
    "cart.delivery.notes": "Special Notes",
    "cart.delivery.notesPlaceholder": "Cutting instructions, preferences, etc.",
    "cart.payment.title": "Secure Payment",
    "cart.payment.desc": "256-bit encrypted transaction.",
    "cart.payment.sandbox": "Sandbox Mode Active",
    "cart.payment.sandboxDesc": "You are in the development environment (Sandbox). To successfully simulate your purchase, click on one of our test cards to autofill the details:",
    "cart.payment.cardName": "Name on Card",
    "cart.payment.cardNamePlaceholder": "e.g. John Doe",
    "cart.payment.cardNumber": "Card Number",
    "cart.payment.cardMonth": "Month",
    "cart.payment.cardYear": "Year",
    "cart.payment.cardCvv": "CVV",
    "cart.payment.total": "Final Total",
    "cart.payment.taxIncluded": "Tax included",
    "cart.payment.buttonPay": "Confirm and Pay",
    "cart.payment.buttonProcessing": "Processing Payment...",
    "cart.payment.securityInfo": "Security guaranteed by OpenPay of BBVA",

    // Home Page
    "home.hero.tagline": "Art of Butchery",
    "home.hero.title": "Montega",
    "home.hero.title2": "",
    "home.hero.desc": "Exclusive selection of premium cuts. The gold standard for your table.",
    "home.hero.buttonCatalog": "Explore Catalog",
    "home.hero.buttonContact": "Direct Contact",
    "home.hero.scroll": "Discover",
    "home.stats.years": "Years of mastery",
    "home.stats.cuts": "Exclusive cuts",
    "home.stats.guarantee": "Guarantee of origin",
    "home.stats.region": "In the region",
    "home.catalog.tagline": "Premium Collection",
    "home.catalog.desc": "Our most exclusive selection. Aged meats and special cuts minutely selected.",
    "home.catalog.beef": "Fine Beef Cuts",
    "home.catalog.pork": "Premium Pork",
    "home.catalog.poultry": "Fresh Poultry",
    "home.catalog.seafood": "From the Sea",
    "home.catalog.button": "View Full Catalog",
    "home.about.title": "Perfection is not rushed, it is cultivated.",
    "home.about.desc1": "At Montega, we understand that an exceptional cut requires mastery, time, and dedication. For over two decades, we have perfected the art of meat selection and aging.",
    "home.about.desc2": "We are not just a butcher shop; we are curators of flavor. We work in close collaboration with the best livestock ranches to guarantee that every piece bearing our seal meets the most rigorous standards of marbling, texture, and flavor.",
    "home.about.sealTitle": "Supreme Quality",
    "home.about.sealDesc": "Signature of excellence",
    "home.feature1.title": "Prime Quality",
    "home.feature1.desc": "We hand-select the best cuts from our workshop for the most demanding palates.",
    "home.feature2.title": "Daily Fresh",
    "home.feature2.desc": "Daily artisanal processing. From our workshop to your table keeping maximum flavor.",
    "home.feature3.title": "VIP Delivery",
    "home.feature3.desc": "Cold chain transport so that your order arrives in optimal conditions.",
    "home.feature4.title": "Family Legacy",
    "home.feature4.desc": "Two decades perfecting the art of fine butchery.",
    "home.contact.title": "Personalized Service",
    "home.contact.desc": "Our expert butchers are at your disposal to advise you on the perfect cut for your occasion.",
    "home.contact.phoneTag": "Direct Line",
    "home.contact.emailTag": "VIP Attention",
    "home.contact.whatsappButton": "WhatsApp Assistance",
    "home.footer.desc": "Excellence in every cut.",

    // Product Detail Page
    "detail.notFound": "Product not found",
    "detail.viewCatalog": "View Catalog",
    "detail.back": "Back to catalog",
    "detail.noStock": "Out of stock",
    "detail.reviews": "reviews",
    "detail.normalPrice": "Regular price",
    "detail.wholesale.applied": "WHOLESALE PRICE APPLIED",
    "detail.wholesale.available": "WHOLESALE PRICE AVAILABLE",
    "detail.wholesale.badge": "Wholesale (40 kilos)",
    "detail.wholesale.benefit": "Wholesale Benefit",
    "detail.wholesale.reached1": "Reach a total of ",
    "detail.wholesale.reached2": " in your cart to activate special pricing. (You have ",
    "detail.wholesale.reached3": "kg)",
    "detail.ingredient": "Main ingredient",
    "detail.qty": "Quantity (kg)",
    "detail.add": "Add",
    "detail.addedSuccess": "{qty} kg of {name} added to cart",

    // Order Success Page
    "success.title": "Payment Successful!",
    "success.desc": "Your order has been confirmed. You will receive a confirmation email and can track its status in \"My Orders\".",
    "success.orderId": "Order #",
    "success.download": "Download PDF Receipt",
    "success.viewOrders": "View My Orders",
    "success.continue": "Continue Shopping",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved === 'es' || saved === 'en') ? saved : 'es';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
